source = ~/.cache/wal/colors-hyprland.conf

background {
    monitor =
    path = $wallpaper
    blur_passes = 2
}

label {
    monitor =
    text = $TIME
    font_size = 64
    color = $foreground
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    outer_color = $color6
    inner_color = $background
    font_color = $foreground
    placeholder_text = Password
    position = 0, -40
    halign = center
    valign = center
}
